language: node_js

node_js:
  - "8.4.0"

script:
  - yarn
  - yarn build

install:
  - yarn global add firebase-tools
  - cd ./functions && yarn

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
