language: node_js

node_js:
  - "8.4.0"

script:
  - yarn
  - yarn run build

install:
  - yarn global add firebase-tools

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
