const CONSTANTS = {
    DEFAULT_LOCAL: 'en-US',
    NORMAL_MSG_DURATION: 3,
    ERROR_MSG_DURATION: 5,
    DEFAULT_NOTICE_PLACEMENT: 'topRight',
    KEY_FOR_AUTH: 'firebase:authUser:AIzaSyCJU9v5f1ygHyvrUGOxueN9OV18VIEuFWA:[DEFAULT]'
};

export default CONSTANTS;
